# Watchlog Cluster Agent RBAC & Deployment (local image)

apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchlog-cluster-agent
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watchlog-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces", "events", "services", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watchlog-cluster-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watchlog-cluster-role
subjects:
  - kind: ServiceAccount
    name: watchlog-cluster-agent
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlog-cluster-agent
  namespace: default
  labels:
    app: watchlog-cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchlog-cluster-agent
  template:
    metadata:
      labels:
        app: watchlog-cluster-agent
    spec:
      serviceAccountName: watchlog-cluster-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
        - name: cluster-agent
          image: watchlog-cluster-agent:latest   # local image
          imagePullPolicy: Never                  # do not pull from registry
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WATCHLOG_APIKEY
              value: "61f5e404a24dc60662757b4c86a4aea0"
            - name: WATCHLOG_SERVER
              value: "http://192.168.1.13:7896"
            - name: WATCHLOG_CLUSTER_NAME
              value: "defaultcluster"
          resources:
            requests:
              cpu:    "200m"
              memory: "256Mi"
            limits:
              cpu:    "1"
              memory: "1Gi"
